import mysql.connector
mydb=mysql.connector.connect(host='localhost',user='root',passwd='123456789',database='program')
mycursor=mydb.cursor()
def shop():
    print('--------------------------------------------')
    timemorn1=input("ENTER THE CHANGED OPENING MORNING TIME: ")
    timeeve1=input("ENTER THE CHANGED CLOSING EVENING TIME: ")
    timenigh1=input("ENTER THE CHANGED OPENING NIGHT TIME: ")
    timenight1=input("ENTER THE CHANGED CLOSING NIGHT TIME: ")
    mycursor.execute("update Jabal_Time set OPENING_TIME='{}' where sno={}".format(timemorn1,1))
    mydb.commit()
    mycursor.execute("update Jabal_Time set CLOSING_TIME='{}' where sno={}".format(timeeve1,1))
    mydb.commit()
    mycursor.execute("update Jabal_Time set OPENING_TIME='{}' where sno={}".format(timenigh1,2))
    mydb.commit()
    mycursor.execute("update Jabal_Time set CLOSING_TIME='{}' where sno={}".format(timenight1,2))
    mydb.commit()
    print()
    print("THE TIMINGS HAVE BEEN UPDATED") 
    print('--------------------------------------------') 
