import pandas as pd
import mysql.connector
mydb=mysql.connector.connect(host='localhost',user='root',passwd='123456789',database='program')
mycursor=mydb.cursor()
def stocks():
    print('--------------------------------------------')
    print()
    print("TO VIEW THE DETAILS OF NEW STOCKS PRESS 1")
    print()
    print("TO VIEW THE DETAILS OF SOLD STOCKS PRESS 2")
    print()
    option=int(input("ENTER YOUR CHOICE: "))
    if option==1:
        print()
        print("TO VIEW THE NEW STOCKS PRESS 1")
        print()
        print('TO SAVE THE CURRENT TABLE AND START A NEW ONE PRESS 2')
        print()
        choice=int(input('ENTER YOUR CHOICE : '))
        if choice==1:
            print('--------------------------------------------')
            mycursor.execute("select * from Ali_Repairs_Stocks")
            tab=mycursor.fetchall()
            df=pd.DataFrame(tab, columns=mycursor.column_names)
            print()
            print(df)
            print()
            print("YOUR REQUIRED TABLE IS SHOWN ABOVE")
            print('--------------------------------------------')  
        elif choice==2:
            print('--------------------------------------------')
            print()
            month=input('ENTER THE MONTH: ')
            year=input('ENTER THE YEAR: ')
            mycursor.execute("select * from Ali_Repairs_stocks")
            tab=mycursor.fetchall()
            df=pd.DataFrame(tab, columns=mycursor.column_names)
            a="C:\\users\\laksh\\ip project\\New Stocks_For_Ali_Repairs\\"+"New Stocks"+' '+month+' '+year+'.csv'    
            df.to_csv(a)
            mycursor.execute("truncate table Ali_Repairs_stocks")
            mydb.commit()   
            print()
            print('THE TABLE HAS BEEN SAVED')
            print('--------------------------------------------')
    elif option==2:
        print('--------------------------------------------')
        print()
        print("TO VIEW THE STOCKS SOLD PRESS 1")
        print()
        print('TO SAVE THE CURRENT TABLE AND START A NEW ONE PRESS 2')
        print()
        choice1=int(input('ENTER YOUR CHOICE : '))
        if choice1==1:
            mycursor.execute("select * from Ali_Repairs_Stocks_Sold")
            tab=mycursor.fetchall()
            df=pd.DataFrame(tab, columns=mycursor.column_names)
            print()
            print(df)
            print()
            print("YOUR REQUIRED TABLE IS SHOWN ABOVE")
            print('--------------------------------------------')
        elif choice1==2:
            print('--------------------------------------------')
            print()
            month=input('ENTER THE MONTH: ')
            year=input('ENTER THE YEAR: ')
            mycursor.execute("select * from Ali_Repairs_stocks_sold")
            tab=mycursor.fetchall()
            df=pd.DataFrame(tab, columns=mycursor.column_names)
            a="C:\\users\\laksh\\ip project\\Stocks Sold_For_Ali_Repairs\\"+"Stocks Sold"+' '+month+' '+year+'.csv'    
            df.to_csv(a)
            mycursor.execute("truncate table Ali_Repairs_stocks_sold")
            mydb.commit()   
            print()
            print('THE TABLE HAS BEEN SAVED')
            print('--------------------------------------------')
            